version: '3'

services:
  frontend:
    build:
      context: frontend
      args:
        - API_URL=http://backend:3001/
        - API_URL_BROWSER=/api
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    depends_on:
      - backend
    container_name: frontend
    restart: always

  backend:
    build: backend
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=redis://redis
    container_name: backend
    restart: always

  proxy:
    build: proxy
    ports:
      - 3002:3002
    environment:
      - PORT=3002

  nginx:
    build: nginx
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=${DOMAIN}
      - FRONTEND_URL=frontend:3000
      - BACKEND_URL=backend:3001
    volumes:
      - ./certbot/certs:/etc/ssl/certs
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    container_name: nginx
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
