version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - API_URL=http://backend:3001/
    depends_on:
      - backend
    container_name: frontend
    restart: always

  backend:
    build: backend
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - MONGODB_URI=${MONGODB_URI}
    container_name: backend
    restart: always

  nginx:
    build: nginx
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=${DOMAIN}
      - FRONTEND_URL=http://frontend:3000/
      - BACKEND_URL=http://backend:3001/
    volumes:
      - ./nginx/certbot/certs:/etc/ssl/certs
      - ./nginx/certbot/letsencrypt:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    container_name: nginx
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
