version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - API_URL=http://backend:3001/
    depends_on:
      - backend
    container_name: frontend
    restart: always

  backend:
    build: backend
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - MONGODB_URI=${MONGODB_URI}
    container_name: backend
    restart: always
