version: '3'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
      args:
        - API_URL=http://backend:3001/
        - API_URL_BROWSER=/api
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    depends_on:
      - backend
    container_name: frontend
    restart: always

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - MONGODB_URI=${MONGODB_URI}
    container_name: backend
    restart: always

  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=${DOMAIN}
      - FRONTEND_URL=frontend:3000
      - BACKEND_URL=backend:3001
    volumes:
      - ../certbot/certs:/etc/ssl/certs
      - ../certbot/letsencrypt:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    container_name: nginx
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
