version: '3'

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ../certbot/letsencrypt:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    depends_on:
      - nginx
    container_name: certbot
    restart: always
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
