name: Proxy

on:
  push:
    paths:
    - proxy/**
  pull_request:
    paths:
    - proxy/**

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm ci
      working-directory: proxy

    - name: Build
      run: npm run build
      working-directory: proxy

    - name: Lint
      run: npm run lint
      working-directory: proxy
